version: "3.4"

services:
  traefik:
    command:
      - --api
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.exposedByDefault=false

      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443

      - --certificatesResolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesResolvers.le.acme.storage=/acme.json
      - --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
    labels:
      # Dashboard
      - traefik.http.routers.traefik.service=api@internal
      # HTTPS
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.entrypoints=websecure
      # Auth
      - traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_AUTH}
      - traefik.http.routers.traefik.middlewares=authtraefik
      # Middleware Redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      # Global redirect to https
      - traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.redirs.entrypoints=web
      - traefik.http.routers.redirs.middleware=redirect-to-https
    volumes:
      - /home/acme.json:/acme.json

  api:
    command: npm start
    labels:
      # HTTPS
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.routers.api.entrypoints=websecure

  mongo:
    command: --auth --timeStampFormat ctime
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      TZ: ${MONGO_TIMEZONE:-America/Sao_Paulo}
    volumes:
      - /home/data/mongo/db:/data/db

  redis:
    command: redis-server --append-only yes --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - /home/data/redis/db:/data
